fix admin fixture, use admin user, fix redirect
rubyforgood/circulate pull request #261
Opened 2020-10-03 15:38 UTC by pineappledreams

### Issue

Fixes https://github.com/rubyforgood/circulate/issues/218

### Summary

1. Implement `require_admin` check at `app/controllers/admin/base_controller.rb`
2. When failed, it will redirect to root_url (tentative)
3. `test/fixtures/users.yml` the admin user is now an actual admin
4. Make admin tests actually use the admin-user.

2020-10-03 20:16 UTC, jim commented on app/controllers/admin/base_controller.rb
> +        redirect_to root_url, warning: "You do not have access to that page."
Good catch!

2020-10-03 20:16 UTC, jim requested changes
Thanks for tackling this one!

We've been trying to move away from fixtures and toward using [FactoryBoty](https://github.com/thoughtbot/factory_bot)factories instead. This wasn't documented anywhere, so there is no way you could have known.

In any case, if you can update the calls to `users(:admin)` to `create(:admin_user)`, we should be able to merge this in.

2020-10-03 20:17 UTC, jim commented
Also, the test failure on this branch has been fixed on the `development` branch, so you can either merge that into this one or we can take care of it when it comes time to merge.

2020-10-04 03:02 UTC, pineappledreams commented
@jim gotcha bud, I will get right to it.

2020-10-04 04:33 UTC, pineappledreams commented
That's strange, I am running the `docker-compose exec web rails test:system` and `rails test` too on my computer but it won't get any errors. Am I missing something here?

2020-10-04 14:08 UTC, jim commented
@pineappledreams Everything is passing locally for me as well. It might be a CI issue, as we've been having some build instability on Circle recently. I'm going to merge this.

2020-10-04 14:09 UTC, jim approved these changes
Thanks for making those revisions!

2020-10-04 14:09 UTC, merged