added form validation for appointment creation
rubyforgood/circulate pull request #287
Opened 2020-10-06 02:36 UTC by renugasaraswathy

Fixes #276 

Please find the screenshots with the error messages displayed.

**Screen 1**: Appointment Form

<img width="1036" alt="Screenshot 2020-10-06 at 7 27 41 AM" src="https://user-images.githubusercontent.com/5791109/95152181-1bf7ee00-07aa-11eb-88bb-8fc2ff4c1add.png">

**Screen 2**: Form is submitted without selecting item and date. Shows respective error messages

<img width="1012" alt="Screenshot 2020-10-06 at 7 27 51 AM" src="https://user-images.githubusercontent.com/5791109/95152187-20240b80-07aa-11eb-8257-ae7dc3404e9a.png">

**Screen 3**: Form is submitted by selecting item and not selecting date. Shows error message only for date.

<img width="1037" alt="Screenshot 2020-10-06 at 7 28 05 AM" src="https://user-images.githubusercontent.com/5791109/95152201-23b79280-07aa-11eb-9c0d-3bffc7724b83.png">

**Screen 4**: Form is submitted by selecting date and not selecting item. Shows error message only for item.

<img width="1031" alt="Screenshot 2020-10-06 at 7 28 43 AM" src="https://user-images.githubusercontent.com/5791109/95152209-274b1980-07aa-11eb-89d9-67eb81895744.png">

**Screen 5**: Form is submitted by selecting date and selecting item. Appointment is saved successfully.

<img width="765" alt="Screenshot 2020-10-06 at 7 29 05 AM" src="https://user-images.githubusercontent.com/5791109/95152215-2a460a00-07aa-11eb-93d5-ba114daeb90e.png">

2020-10-06 02:57 UTC, rkim00 commented
Looks great! Thanks for all the screen shots, and thanks for your work!

2020-10-08 01:37 UTC, renugasaraswathy commented
Hi @rkim00, Thank you for your feedback. Could you please get it reviewed by the tech leads. 

Thanks

2020-10-09 04:01 UTC, mdworken requested changes
Looks like a really excellent start! I left a couple comments within the PR on some code that I'm not sure still needs to be in here.

My only other comment is that we should probably use the built in rails presence validators for these, unless there's a specific reason not to.

2020-10-09 04:03 UTC, renugasaraswathy commented on app/models/appointment.rb
> +  attr_accessor :time_range_string
Yes right, will remove it

2020-10-09 04:03 UTC, renugasaraswathy commented on app/models/appointment.rb
> +    puts holds.inspect
Yes. Missed removing the puts statements, will remove them.

2020-10-09 04:12 UTC, renugasaraswathy commented on app/views/appointments/_form.html.erb
> +            <td><%= check_box_tag("appointment[loan_ids][]", loan.id, (@appointment.loans.include?(loan))) %></td>
Forms wont be pre-filled when user sees the page for the first time. 

It is pre-filled only when the form is not saved and there are errors. It is a good user experience if it is pre-filled and not ask the user to fill the entire form when a mistake is made.

2020-10-09 04:21 UTC, renugasaraswathy commented on app/controllers/appointments_controller.rb
> +      @loans = current_user.member.loans.includes(:item).checked_out
These variables are needed to render the check boxes when form has errors.

When there are errors, the flow would be

Controller new -> new.html.erb -> submit form -> controller create method -> if errors -> renders new.html.erb

So whatever variables used in new.html.erb, to be set values in 'def create' if there are errors.

2020-10-09 04:23 UTC, renugasaraswathy commented
Hi @mdworken, thank you so much for your time and feedback. I have given my replies in the PR. 

Thanks

2020-10-13 00:45 UTC, renugasaraswathy commented
@jim @johnksawers could you review this PR. Thanks.

2020-10-13 01:07 UTC, jim commented
@renugasaraswathy Thanks for this contribution! I will review this shortly.

2020-10-13 04:44 UTC, jim approved these changes
Tested and works as described in the story! Thanks very much for the contribution.

2020-10-13 04:44 UTC, merged

2020-10-13 23:37 UTC, rkim00 commented
@jim These changes don't seem to be showing up in staging. Is there any reason they might have gotten lost?

2020-10-14 19:32 UTC, rkim00 commented
This now appears to be working in staging.