Fixed footer display on Items page.
rubyforgood/circulate pull request #380
Opened 2020-10-27 18:32 UTC by efgalvao

Changed footer specs to fix issue #374

# Why it is important

Fixes the issue #374.

# UI Change Screenshot

After
![Screenshot_2020-10-27 Circulate](https://user-images.githubusercontent.com/61836657/97345865-64ff0780-1869-11eb-9a1b-7d27b783fbd0.png)

# Implementation notes

* Choose for a fixed footer.

2020-11-01 15:40 UTC, jim requested changes
Thanks for the contribution! This implementation works well on the item page, but on the item index it causes the footer to appear on top of the listing. We want the footer to appear at the bottom of the page and not on top of the other page content.

I'd like to see if we can fix this without adding more CSS. I think the issue is related to the structure of the markup on these pages and not on the styling. Here's the structure of the item index, which is displaying properly:

![Screenshot 2020-11-01 093710](https://user-images.githubusercontent.com/3331/97807376-fbdf1180-1c25-11eb-8cce-52d5334c1d86.png)

And here it is for the item page, where the footer is showing up incorrectly:

![Screenshot 2020-11-01 093556](https://user-images.githubusercontent.com/3331/97807373-f8e42100-1c25-11eb-8e41-377f4fabb498.png)

2020-11-01 22:29 UTC, efgalvao commented
![Screenshot_2020-11-01 Circulate](https://user-images.githubusercontent.com/61836657/97817007-6e78dd00-1c78-11eb-98b7-dacdaa8b88ca.png)
![Screenshot_2020-11-01 Circulate(1)](https://user-images.githubusercontent.com/61836657/97817009-6f117380-1c78-11eb-9324-712eceeeb296.png)
I think now is the way you wanted.

2020-11-02 01:59 UTC, jim approved these changes

2020-11-02 01:59 UTC, jim commented
@efgalvao This is great! Thank you for making those changes.

2020-11-02 01:59 UTC, merged